### ISSUE TITLE
google sheets api batchGet only accepts a single range

### ISSUE THREAD

**Issue by BebopChrome** [omarryhan/aiogoogle#58] opened 2021-04-28 15:24 UTC
_sheetServiceAsync = await aiogoogle.discover("sheets", "v4")
resp = await aiogoogle.as_service_account(_sheetServiceAsync .spreadsheets.values.batchGet(spreadsheetId=id, ranges=ranges))

value of ranges should be a list ie ["'DARK'!A4:I83", "'OHW'!A4:I83", "'JESOS'!A4:I83"]
ranges only accepts a single string range making this no different than get.

**Comment by omarryhan** [comment] 2021-04-28 17:41
I just checked the docs and the discovery document, and it says it should be a string.
Here's the description: "The A1 notation or R1C1 notation of the range to retrieve values from."

Docs: https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets.values/batchGet
Discovery doc: https://www.googleapis.com/discovery/v1/apis/sheets/v4/rest

A potential solution:

Your parameters are validated before they're sent to Google. If you want to bypass that, you can pass `validate=False` after ranges and see if that'll work.
If it does, then you should report this error on one of Google's official API client libraries.

**Comment by BebopChrome** [comment] 2021-04-28 19:01
This appears to be intentional by google as each range in the list is a string. batchClear uses the same notation but the 'Try It' option recognizes that ranges is a list of strings and allows me to add as many strings as I like to test. I could use the batchGetByDataFilter option but it uses a body option that is not listed in parameters so your api does not allow body to be included in the command as it is in the example. please see if there is something you can do to make one of these work. This is a great api, but without one of these batchGet functions I can not use it. validate = False did not work. This works fine on googles python library, but I need async.

**Comment by BebopChrome** [comment] 2021-04-28 19:07
The name ending in [] as in ranges[] and clearedRanges[] appears to be the only way to auto distinguish a list of strings from a string and appears to be consistent with how lists are handled in the api

**Comment by omarryhan** [comment] 2021-04-28 20:04
Why did `validate=False` not work? Maybe I can help you with that.

> I could use the batchGetByDataFilter option but it uses a body option that is not listed in parameters so your api does not allow body to be included in the command as it is in the example

You can pass a body. It's named differently here though. If you want to pass a JSON object in the body you should pass it as `json={...}`. Otherwise, you should pass the body as `data=...`.

> The name ending in [] as in ranges[] and clearedRanges[] appears to be the only way to auto distinguish a list of strings from a string and appears to be consistent with how lists are handled in the api

This is true. However, this library only uses the discovery document as a reference on how to build the request. And unfortunately, the discovery doc doesn't have "[]" in it.

**Comment by omarryhan** [comment] 2021-04-28 20:13
Oh shoot, it just hit me that you can't pass arrays in the URL. That's probably why the type isn't specified as an array by Google. As a quick fix you can join the array yourself using a comma. i.e. `["'DARK'!A4:I83", "'OHW'!A4:I83", "'JESOS'!A4:I83"].join(',')`.

Meanwhile, I'll check and see if we should be auto-joining all arrays that are passed as URL params.

**Comment by BebopChrome** [comment] 2021-04-28 20:49
validate=False did work but I still get an error in the response. I used google console to see how the 'Try It' code requests and it breaks the array up into a series of ?ranges=%27IR%27!A4%3AI83&ranges=%27EQ%27!A4%3AI83. I will try json or data instead of body

**Comment by BebopChrome** [comment] 2021-04-28 21:18
I was able to get batchGetByDataFilter to run without error using data and json instead of body but it did not return any values.

**Comment by BebopChrome** [comment] 2021-04-28 21:24
I tried converting it into a comma delimited string but google could not parse it. joining all the strings with '&range=' would work but the api encodes it so it doesn't work

**Comment by omarryhan** [comment] 2021-04-29 13:19
I also used the try me section and when I inspected the URL in the dev console it was delimited by a comma. Very weird.

Unfortunately, passing duplicate URL parameters is not yet supported by this lib.

The quickest fix I can think of is that you can pass it manually. 

```python
# First build the request with only one range

req = spreadsheets.values.batchGet(ranges="'DARK'!A4:I83")

# Then add the rest manually to the URL

req.url = req.url + other_ranges

# Now send the request

res = await aiogoogle.as_service_account(req)

```

> I was able to get batchGetByDataFilter to run without error using data and json instead of body but it did not return any values.

You should only use one of them. If you're passing a JSON body, use only the JSON option.

Please let me know what works for you in the end so I can fix it as soon as I can.

Thanks.

**Comment by omarryhan** [comment] 2021-04-29 13:30
I just checked. The parameter is marked as repeatable. I'll try and add support for that as soon as I can. Meanwhile, please use the workaround I mentioned in the comment above and let me know if something goes wrong. Thanks.

**Comment by omarryhan** [comment] 2021-04-29 13:32
I just remembered, this is actually the same issue as #52

**Comment by BebopChrome** [comment] 2021-04-29 14:45
when using batchGetByDataFilter I only tested json and data one at a time. json worked if I passed the python list directly and data worked if I converted it to a json string. Neither returned any values

**Comment by omarryhan** [comment] 2021-04-29 14:51
Glad it worked.

Can you post your code for batchGetByDataFilter?

**Comment by BebopChrome** [comment] 2021-04-29 14:56
I add the code for the data version above. For json I used:
 
    datafilters = []
    for batchrange in ranges:
        datafilter = {"a1Range":batchrange}
        datafilters.append(datafilter)
    batch_get_values_by_data_filter_request_body = {
        'data_filters': datafilters
    }
    
    resp = await aiogoogle.as_service_account(_sheetServiceAsync.spreadsheets.values.batchGetByDataFilter(spreadsheetId=id, json=batch_get_values_by_data_filter_request_body))

**Comment by BebopChrome** [comment] 2021-04-29 15:52
From https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets.values/batchGet 'Try this API' use:
spreadsheetID: 1S_WJadzTwvA4oYZ7kJlzkYs6dIxPc1DWbFF_kcLO1
ranges 1: 'IR'!A4:I83
add
ranges 2: 'EQ'!A4:I83
execute
google console (network) returns:
https://content-sheets.googleapis.com/v4/spreadsheets/1S_WJadzTwvA4oYZ7kJlzkYs6dIxPc1DWbFF_kcLO1-Y/values:batchGet?ranges=%27IR%27!A4%3AI83&ranges=%27EQ%27!A4%3AI83&key=abcd
For an example of how it uses multiple ranges in the querystring

**Comment by BebopChrome** [comment] 2021-04-30 15:00
I also found that BatchUpdae did not work with body=body but unlike batchGetByDataFilter i was able to get it to work with json=body

        body = {
            "valueInputOption": "USER_ENTERED",
            "data": [{"range": r, "values": v} for r, v in zip(ranges, values)]
        }
        req = self._spreadsheetAsync.values.batchUpdate(spreadsheetId=id, json=body)
        resp = await self.aiogoogle.as_service_account(req)

**Comment by omarryhan** [comment] 2021-04-30 21:20
Not sure why the `batchGetByDataFilter` isn't working for you. I think everything check out. Might be a problem with your actual filter (that is: the filter correctly returned nothing)? Did you double check?

> I also found that BatchUpdae did not work with body=body but unlike batchGetByDataFilter i was able to get it to work with json=body

Yeah, that's because this lib doesn't read the `body` parameter as a JSON body. JSON body should be passed as `json=` instead of `body=`. When you pass body, Aiogoogle will add it as a URL argument.

**Comment by omarryhan** [comment] 2021-05-02 05:43
I'll close this issue because it's a duplicate of #52.
Please open a new issue if you face further problems. Thanks!

**Closed by omarryhan** 2021-05-02 05:43 UTC
Labels: feature

**Comment by omarryhan** [comment] 2021-05-06 10:16
Hey, I found a way simpler solution to this problem and I just pushed the fix.

The solution is to pass an array instead of a MultiDict. I iterated over all of Google's discovery documents and checked if Google ever asks for an actual serialized array, and as expected, they don't. So now, whenever a user passes an array, Aiogoogle would check if this parameter is repeatable. If it is, it would break them into separate URL args, instead of serializing the whole array as a JSON array. If it isn't, it's treated like before (validates with an error, and if validation is turned off, it would serialize the whole array as a JSON array). Hope I explained this well.

tl;dr you can now pass `ranges=['range1', 'range2']` or `ranges='range1'` instead of the workaround I mentioned above.
