### ISSUE TITLE
How to do batch request?

### ISSUE THREAD

**Issue by kshilov** [omarryhan/aiogoogle#34] opened 2020-09-11 12:48 UTC
Based on google docs (https://developers.google.com/gmail/api/guides/batch) there is possible to do a batch request. 

I found batch_requests method in the current repo but it's not implemented.

What's the right way to do batch request with aiogoogle?

**Comment by omarryhan** [comment] 2020-09-12 15:11
Duplicate of #15 

I replied to you there.

**Closed by omarryhan** 2020-09-12 15:11 UTC
